#!/bin/bash

for file in libs/*; do
. "$file"
done

preFetchChrome

packages $packagesDevelopment $packagesDesktop $packagesWork $packagesCommandLine $packagesOffice $packagesChromePrereqs

installChrome
