#!/bin/bash

startDir=`pwd`
for file in `ls -1 libs/*| sort`; do
. "$startDir/$file"
done

preFetchChrome

packages $packagesDevelopment $packagesDesktop $packagesWork $packagesCommandLine $packagesOffice $packagesChromePrereqs

installChrome
