#!/bin/bash
# Build a devuan chroot using debootstrap.

chrootLabel="devuan-phone"

. .fpStarter

packages=`chrootPackages $packagesDevuan $packagesDevelopment $packagesDesktopDevuan $packagesWork $packagesCommandLine $packagesChromePrereqs $packagesVNCServer $packagesKDE $packagesOffice`

chrootVars
chrootBuildAll

chrootVars

