#!/bin/bash
# Mount a partition within an image. 
# Syntax:
#   $0 imageFile parititionNumber mountPoint

. .fpStarter

while read build; do
	fileName=~/chroots/build/$build/etc/issue
	if [ -f "$fileName" ]; then
		description=`head -n1 $fileName`
	else
		description=''
	fi
	
	echo "$build	$description"
done < <(ls -1 ~/chroots/build/$1)
