#!/bin/bash
# Mount a partition within an image. 
# Syntax:
#   $0 imageFile parititionNumber mountPoint

. .fpStarter

while read build; do
	echo "$build	`head -n1 ~/chroots/build/$build/etc/issue`"
done < <(ls -1 ~/chroots/build/$1)
