#!/bin/bash
# Enteres a mounted chroot directory.
# Syntax:
#   $0 [buildDirectory]

. .fpStarter

requireParameters "$0" "$0"

chrootUseBuildDir "$1"



chrootRun kate kwrite konsole vim dev-vcs/git
