#!/bin/bash
# Mount a partition within an image. 
# Syntax:
#   $0 imageFile parititionNumber mountPoint

. .fpStarter

while read build; done
	echo "$build	`head -n1 ~/chroots/builds/$build`"
done < <(ls -1 ~/chroots/build/$1)
