#!/bin/bash
# Unmount extra mounts from a mounted chroot directory.
# Syntax:
#   $0 [buildDirectory]

. .fpStarter

requireParameters "$0" "$0"

chrootImage "$1"
chrootUseBuildDir "$2"

chrootUmountImage
