#!/bin/bash
# Mount extra mounts from a mounted chroot directory.
# Syntax $0 [image [directory]]
#   If image is absent, it will be assumed to be the latest one.
#   If directory is absent, it will be assumed to be the latest one.

. .fpStarter

requireParameters "$0" "$0"

chrootUseBuildDir "$1"

tail -F "$mountPoint/var/log/fpBuild.log"
