#!/bin/bash
# Clean all builds and images. Use with extreme caution.

. .fpStarter

warn "This will destroy all build dirs (not important) and images (important)."

rm -Rvf ~/chroots/build/* ~/chroots/images/*
