#!/bin/bash
# Mount a partition within an image. 
# Requires parameters: $0 imageFile parititionNumber mountPoint

if [ "$2" == "" ]; then
	tail -n+2 $0 | head -n 2
	exit 1
else
	tail -n+2 $0 | head -n 1
fi

. .fpStarter

mountSubParition "$1" "$2" "$3"
