#!/bin/bash
# Build a devuan chroot using debootstrap.

chrootLabel="debian-phone"

. .fpStarter

chrootRelease="wheezy"
chrootMirror=""
packages=`chrootPackages $packagesDevuan $packagesDevelopment $packagesDesktopDevuan $packagesWork $packagesCommandLine $packagesChromePrereqs $packagesVNCServer $packagesKDE`

chrootVars
chrootBuildAll

chrootVars

