#!/bin/bash
# Build a gentoo chroot using debootstrap. Normally you'll want to use gentoo-armhf-desktop. But if you have resource issues, you may want to use part1 and part2 with qemu.

chrootLabel="gentoo-phone"

. .fpStarter

blocks="8K"

packages=''
arch=armv7hl

chrootVars

# Do this intial stuff to create the image.
	# Prep
	chrootUseBuildDir "$1"
	
	
	# Configure.
	chrootGentooHackPortageConfigIssue
	#chrootGentooKDEProfile
	chrootGentooSetupDNS
	chrootGentooRemoveMMX
	chrootGentooSetupUSEFlags
	chrootGentooPlaceHardCodedConfigs
	
	# Build build tools.
	chrootGentooBuildBuildTools
	
	# Build graphical stuff
	chrootGentooBasicGraphicalChrooting
	chrootGentooInstallKDE
	
	
	# Cleanup.
	chrootUnMountExtras

chrootVars

