#!/bin/bash
# Build a devuan chroot using debootstrap.

chrootLabel="gentoo-amd64"

. .fpStarter

chrootGentooStage3URL="http://gentoo.ussg.indiana.edu/releases/amd64/autobuilds/current-stage3-amd64/"

packages=''

chrootVars
chrootGentooBuildAll

chrootVars

